name: Manage Branches

on:
  workflow_dispatch: # 수동으로만 실행 가능하게 설정

jobs:
  manage-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Fetch all branches
        run: git fetch --all

      - name: Delete team member branches
        run: |
          branches=("hyerin" "aryeong" "seungjin" "chanhee") # 팀원의 브랜치 이름 리스트
          for branch in "${branches[@]}"; do
            git push origin --delete $branch || true # 원격 브랜치 삭제
          done

      - name: Recreate team member branches from dev
        run: |
          branches=("hyerin" "aryeong" "seungjin" "chanhee") # 팀원의 브랜치 이름 리스트
          for branch in "${branches[@]}"; do
            git checkout -b $branch
            git push origin $branch
          done
